version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: contactapp
      MONGO_INITDB_ROOT_PASSWORD: ContactApp123!
    ports:
      - 27017:27017
    volumes:
    - mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: contactapp
      ME_CONFIG_MONGODB_ADMINPASSWORD: ContactApp123!
      ME_CONFIG_MONGODB_URL: mongodb://contactapp:ContactApp123!@mongo:27017/
volumes:
  mongo-volume:
